# Generated by Django 6.0 on 2026-01-09 02:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("checking", "Checking"),
                            ("savings", "Savings"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("corporate_card", "Corporate Card"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("mask", models.CharField(blank=True, max_length=10)),
                ("institution_name", models.CharField(blank=True, max_length=255)),
                (
                    "plaid_account_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "plaid_item_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("auto_categorize", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "bank_accounts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("merchant_name", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("software", "Software Subscription"),
                            ("saas", "SaaS"),
                            ("cloud", "Cloud Services"),
                            ("communication", "Communication"),
                            ("other", "Other"),
                            ("uncategorized", "Uncategorized"),
                        ],
                        default="uncategorized",
                        max_length=20,
                    ),
                ),
                ("is_subscription_related", models.BooleanField(default=False)),
                ("is_matched", models.BooleanField(default=False)),
                ("match_confidence", models.FloatField(default=0)),
                ("matched_by", models.CharField(blank=True, max_length=50)),
                ("external_id", models.CharField(max_length=255, unique=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "bank_transactions",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="EmailScanConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("scan_invoices", models.BooleanField(default=True)),
                ("scan_receipts", models.BooleanField(default=True)),
                ("scan_welcome_emails", models.BooleanField(default=True)),
                ("mailboxes", models.JSONField(blank=True, default=list)),
                ("sender_patterns", models.JSONField(blank=True, default=list)),
                ("subject_patterns", models.JSONField(blank=True, default=list)),
                ("scan_from_date", models.DateField(blank=True, null=True)),
                ("last_scan", models.DateTimeField(blank=True, null=True)),
                ("last_scan_result", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "email_scan_configs",
            },
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("google_workspace", "Google Workspace"),
                            ("microsoft_365", "Microsoft 365"),
                            ("okta", "Okta"),
                            ("azure_ad", "Azure Active Directory"),
                            ("onelogin", "OneLogin"),
                            ("jumpcloud", "JumpCloud"),
                            ("slack", "Slack"),
                            ("teams", "Microsoft Teams"),
                            ("quickbooks", "QuickBooks"),
                            ("xero", "Xero"),
                            ("expensify", "Expensify"),
                            ("concur", "SAP Concur"),
                            ("brex", "Brex"),
                            ("ramp", "Ramp"),
                            ("plaid", "Plaid (Bank Feeds)"),
                            ("stripe", "Stripe"),
                            ("workday", "Workday"),
                            ("bamboohr", "BambooHR"),
                            ("gusto", "Gusto"),
                            ("rippling", "Rippling"),
                            ("webhook", "Custom Webhook"),
                            ("api", "Custom API"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Setup"),
                            ("connected", "Connected"),
                            ("disconnected", "Disconnected"),
                            ("error", "Error"),
                            ("expired", "Token Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("credentials", models.JSONField(blank=True, default=dict)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("sync_enabled", models.BooleanField(default=True)),
                ("sync_interval_minutes", models.IntegerField(default=60)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("last_sync_status", models.CharField(blank=True, max_length=255)),
                ("last_sync_error", models.TextField(blank=True)),
                ("sync_subscriptions", models.BooleanField(default=True)),
                ("sync_users", models.BooleanField(default=False)),
                ("sync_transactions", models.BooleanField(default=False)),
                ("sync_usage", models.BooleanField(default=False)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("webhook_url", models.URLField(blank=True, null=True)),
                (
                    "webhook_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "integrations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationSync",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("records_processed", models.IntegerField(default=0)),
                ("records_created", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("records_failed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                ("sync_type", models.CharField(blank=True, max_length=100)),
                ("sync_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "integration_syncs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SlackNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel_id", models.CharField(max_length=255)),
                ("channel_name", models.CharField(max_length=255)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("all", "All Notifications"),
                            ("alerts", "Alerts Only"),
                            ("renewals", "Renewals Only"),
                            ("recommendations", "Recommendations"),
                            ("workflows", "Workflow Updates"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("min_severity", models.CharField(default="warning", max_length=20)),
                (
                    "min_savings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("departments", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "slack_notifications",
            },
        ),
        migrations.CreateModel(
            name="SSOConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("app_name", models.CharField(max_length=255)),
                ("app_id", models.CharField(blank=True, max_length=255)),
                ("app_type", models.CharField(blank=True, max_length=100)),
                ("assigned_users", models.IntegerField(default=0)),
                ("active_users", models.IntegerField(default=0)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sso_connections",
                "ordering": ["app_name"],
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("secret", models.CharField(max_length=255)),
                ("events", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("max_retries", models.IntegerField(default=3)),
                ("retry_interval_seconds", models.IntegerField(default=60)),
                ("total_deliveries", models.IntegerField(default=0)),
                ("successful_deliveries", models.IntegerField(default=0)),
                ("failed_deliveries", models.IntegerField(default=0)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                ("last_failure", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "webhooks",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("response_status", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("attempts", models.IntegerField(default=0)),
                ("next_retry", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "webhook_deliveries",
                "ordering": ["-created_at"],
            },
        ),
    ]
