# Generated by Django 6.0 on 2026-01-09 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("integrations", "0001_initial"),
        ("services", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="bank_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="integrations.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_transactions",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transactions",
                to="services.subscription",
            ),
        ),
        migrations.AddField(
            model_name="emailscanconfig",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_scan_configs",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="integration",
            name="connected_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="connected_integrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="integration",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="integrations",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="emailscanconfig",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_configs",
                to="integrations.integration",
            ),
        ),
        migrations.AddField(
            model_name="bankaccount",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_accounts",
                to="integrations.integration",
            ),
        ),
        migrations.AddField(
            model_name="integrationsync",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="syncs",
                to="integrations.integration",
            ),
        ),
        migrations.AddField(
            model_name="slacknotification",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slack_notifications",
                to="integrations.integration",
            ),
        ),
        migrations.AddField(
            model_name="slacknotification",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slack_notifications",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="ssoconnection",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sso_connections",
                to="integrations.integration",
            ),
        ),
        migrations.AddField(
            model_name="ssoconnection",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sso_connections",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="ssoconnection",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sso_connections",
                to="services.subscription",
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhooks",
                to="users.organization",
            ),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="webhook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="integrations.webhook",
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["organization", "transaction_date"],
                name="bank_transa_organiz_2a6153_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="banktransaction",
            index=models.Index(
                fields=["merchant_name"], name="bank_transa_merchan_dcf144_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="integration",
            unique_together={("organization", "type", "name")},
        ),
    ]
