# Generated by Django 6.0 on 2026-01-09 02:46

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("renewal", "Upcoming Renewal"),
                            ("budget_warning", "Budget Warning"),
                            ("budget_exceeded", "Budget Exceeded"),
                            ("unused_license", "Unused Licenses"),
                            ("low_usage", "Low Usage"),
                            ("contract_expiry", "Contract Expiring"),
                            ("price_increase", "Price Increase Detected"),
                            ("new_subscription", "New Subscription Discovered"),
                            ("redundancy", "Redundancy Detected"),
                            ("security", "Security Alert"),
                            ("integration", "Integration Issue"),
                            ("custom", "Custom Alert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("snoozed", "Snoozed"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("action_required", models.BooleanField(default=False)),
                ("action_url", models.URLField(blank=True, null=True)),
                (
                    "financial_impact",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("trigger_date", models.DateField(blank=True, null=True)),
                ("trigger_threshold", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BudgetTarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("warning_threshold", models.IntegerField(default=80)),
                ("critical_threshold", models.IntegerField(default=100)),
                (
                    "current_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "budget_targets",
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="CostRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("payment", "Payment"),
                            ("refund", "Refund"),
                            ("credit", "Credit"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("invoice_url", models.URLField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("source", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cost_records",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cancel", "Cancel Subscription"),
                            ("downgrade", "Downgrade Plan"),
                            ("reduce_licenses", "Reduce Licenses"),
                            ("consolidate", "Consolidate Tools"),
                            ("reassign", "Reassign Licenses"),
                            ("renegotiate", "Renegotiate Contract"),
                            ("switch", "Switch Provider"),
                            ("upgrade", "Upgrade Plan"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("detailed_analysis", models.TextField(blank=True)),
                (
                    "estimated_savings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("savings_period", models.CharField(default="annual", max_length=20)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "confidence_score",
                    models.FloatField(default=0, help_text="AI confidence 0-100"),
                ),
                ("action_items", models.JSONField(blank=True, default=list)),
                ("implementation_steps", models.JSONField(blank=True, default=list)),
                ("risks", models.JSONField(blank=True, default=list)),
                ("ai_model_version", models.CharField(blank=True, max_length=100)),
                ("data_points_used", models.JSONField(blank=True, default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "recommendations",
                "ordering": ["-estimated_savings", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RedundancyGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("detected", "Detected"),
                            ("reviewing", "Under Review"),
                            ("dismissed", "Dismissed"),
                            ("consolidating", "Consolidating"),
                            ("resolved", "Resolved"),
                        ],
                        default="detected",
                        max_length=20,
                    ),
                ),
                (
                    "overlap_score",
                    models.FloatField(default=0, help_text="0-100 overlap percentage"),
                ),
                ("overlapping_features", models.JSONField(blank=True, default=list)),
                (
                    "potential_savings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("recommended_action", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "redundancy_groups",
                "ordering": ["-potential_savings"],
            },
        ),
        migrations.CreateModel(
            name="RedundancyGroupMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, help_text="Recommended to keep"),
                ),
                ("usage_score", models.FloatField(default=0)),
                ("cost_effectiveness_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "redundancy_group_members",
            },
        ),
        migrations.CreateModel(
            name="SavingsReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "optimized_spend",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_savings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("savings_by_type", models.JSONField(blank=True, default=dict)),
                ("savings_by_department", models.JSONField(blank=True, default=dict)),
                ("savings_by_action", models.JSONField(blank=True, default=dict)),
                ("subscriptions_analyzed", models.IntegerField(default=0)),
                ("recommendations_generated", models.IntegerField(default=0)),
                ("recommendations_implemented", models.IntegerField(default=0)),
                (
                    "report_file",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "savings_reports",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareVendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("logo", models.URLField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("productivity", "Productivity"),
                            ("communication", "Communication"),
                            ("development", "Development"),
                            ("design", "Design"),
                            ("marketing", "Marketing"),
                            ("sales", "Sales"),
                            ("hr", "HR & Recruiting"),
                            ("finance", "Finance & Accounting"),
                            ("security", "Security"),
                            ("analytics", "Analytics"),
                            ("project_mgmt", "Project Management"),
                            ("crm", "CRM"),
                            ("cloud", "Cloud Infrastructure"),
                            ("database", "Database"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                ("billing_domains", models.JSONField(blank=True, default=list)),
                (
                    "avg_price_per_user",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "software_vendors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("custom_category", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("cancelled", "Cancelled"),
                            ("trial", "Trial"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "discovery_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("email", "Email Scan"),
                            ("sso", "SSO/Identity Provider"),
                            ("bank_feed", "Bank/Card Feed"),
                            ("expense", "Expense System"),
                            ("integration", "Third-Party Integration"),
                            ("ai", "AI Discovery"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "is_shadow_it",
                    models.BooleanField(
                        default=False,
                        help_text="Discovered outside official procurement",
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("semi_annual", "Semi-Annual"),
                            ("annual", "Annual"),
                            ("custom", "Custom"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("total_licenses", models.IntegerField(default=0)),
                ("used_licenses", models.IntegerField(default=0)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("renewal_date", models.DateField(blank=True, null=True)),
                ("auto_renew", models.BooleanField(default=True)),
                (
                    "contract_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "contract_document",
                    models.FileField(blank=True, null=True, upload_to="contracts/"),
                ),
                ("terms", models.JSONField(blank=True, default=dict)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("login_url", models.URLField(blank=True, null=True)),
                ("admin_url", models.URLField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending Activation"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "external_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "external_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "license_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscription_users",
                "ordering": ["-last_used"],
            },
        ),
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("feature_use", "Feature Use"),
                            ("api_call", "API Call"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("feature", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "db_table": "usage_events",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UsageMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("active_users", models.IntegerField(default=0)),
                ("total_users", models.IntegerField(default=0)),
                ("new_users", models.IntegerField(default=0)),
                ("churned_users", models.IntegerField(default=0)),
                ("total_sessions", models.IntegerField(default=0)),
                ("total_duration_minutes", models.IntegerField(default=0)),
                ("avg_session_duration", models.FloatField(default=0)),
                ("feature_usage", models.JSONField(blank=True, default=dict)),
                ("engagement_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "usage_metrics",
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("cancellation", "Cancellation Request"),
                            ("license_change", "License Change"),
                            ("new_subscription", "New Subscription"),
                            ("renewal", "Renewal Decision"),
                            ("budget_approval", "Budget Approval"),
                            ("reassignment", "License Reassignment"),
                            ("consolidation", "Tool Consolidation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("justification", models.TextField(blank=True)),
                ("request_data", models.JSONField(blank=True, default=dict)),
                (
                    "financial_impact",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workflows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_order", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "workflow_steps",
                "ordering": ["workflow", "step_order"],
            },
        ),
    ]
