# Generated by Django 6.0.3 on 2026-03-15 11:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_initial"),
        ("users", "0002_rename_timezone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("renewal_approaching", "Renewal Approaching"),
                            ("low_usage", "Low Usage"),
                            ("budget_exceeded", "Budget Exceeded"),
                            ("new_subscription", "New Subscription"),
                            ("recommendation_created", "Recommendation Created"),
                            ("scheduled", "Scheduled"),
                            ("threshold", "Threshold"),
                        ],
                        max_length=40,
                    ),
                ),
                ("trigger_config", models.JSONField(blank=True, default=dict)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("send_email", "Send Email"),
                            ("send_slack", "Send Slack"),
                            ("create_task", "Create Task"),
                            ("update_subscription", "Update Subscription"),
                            ("create_approval", "Create Approval"),
                            ("webhook", "Webhook"),
                            ("notify", "Notify"),
                        ],
                        max_length=40,
                    ),
                ),
                ("action_config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("run_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_automation_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_workflows",
                        to="users.organization",
                    ),
                ),
            ],
            options={
                "db_table": "automation_workflows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("trigger_reason", models.CharField(blank=True, max_length=500)),
                ("steps_completed", models.IntegerField(default=0)),
                ("total_steps", models.IntegerField(default=1)),
                ("error_message", models.TextField(blank=True)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="services.automationworkflow",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="automationworkflow",
            index=models.Index(
                fields=["organization", "is_active"],
                name="automation__organiz_658e86_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationworkflow",
            index=models.Index(
                fields=["organization", "trigger"],
                name="automation__organiz_35f93a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["workflow", "status"], name="workflow_ex_workflo_05fdb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["workflow", "started_at"], name="workflow_ex_workflo_fa04c2_idx"
            ),
        ),
    ]
