# Generated by Django 6.0 on 2026-01-09 02:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("deleted", "Deleted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("file_size", models.BigIntegerField(default=0)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("tables_backed_up", models.JSONField(default=list)),
                ("record_counts", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("triggered_by", models.CharField(default="scheduled", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "backups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BackupSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Backup"),
                            ("incremental", "Incremental"),
                            ("differential", "Differential"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("include_subscriptions", models.BooleanField(default=True)),
                ("include_usage_data", models.BooleanField(default=True)),
                ("include_cost_records", models.BooleanField(default=True)),
                ("include_recommendations", models.BooleanField(default=True)),
                ("include_workflows", models.BooleanField(default=True)),
                ("include_integrations", models.BooleanField(default=False)),
                ("schedule_time", models.TimeField()),
                ("schedule_day_of_week", models.IntegerField(blank=True, null=True)),
                ("schedule_day_of_month", models.IntegerField(blank=True, null=True)),
                ("retention_days", models.IntegerField(default=30)),
                ("max_backups", models.IntegerField(default=10)),
                ("storage_location", models.CharField(default="s3", max_length=255)),
                ("storage_path", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("last_backup", models.DateTimeField(blank=True, null=True)),
                ("next_backup", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "backup_schedules",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("subscriptions", "Subscriptions"),
                            ("usage", "Usage Data"),
                            ("costs", "Cost Records"),
                            ("recommendations", "Recommendations"),
                            ("savings", "Savings Report"),
                            ("full", "Full Export"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("json", "JSON"),
                            ("csv", "CSV"),
                            ("excel", "Excel"),
                            ("pdf", "PDF"),
                        ],
                        default="csv",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.BigIntegerField(default=0)),
                ("download_url", models.URLField(blank=True)),
                ("download_expires_at", models.DateTimeField(blank=True, null=True)),
                ("progress", models.IntegerField(default=0)),
                ("records_exported", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "data_exports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("subscriptions", "Subscriptions"),
                            ("users", "Users"),
                            ("cost_records", "Cost Records"),
                            ("mixed", "Mixed Data"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validating", "Validating"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("source_file", models.FileField(upload_to="imports/")),
                ("source_file_name", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(default=0)),
                ("column_mapping", models.JSONField(blank=True, default=dict)),
                ("total_rows", models.IntegerField(default=0)),
                ("processed_rows", models.IntegerField(default=0)),
                ("successful_rows", models.IntegerField(default=0)),
                ("failed_rows", models.IntegerField(default=0)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("processing_errors", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("can_rollback", models.BooleanField(default=True)),
                ("rollback_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "import_jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
